In [21]:
import pandas as pd
import json
from unidecode import unidecode

In [22]:
df = pd.read_csv("../datasets_models/data.csv")
comarcas_df = pd.read_csv("../comarques.csv")

In [50]:
df.precip.max()

388.2

In [18]:
df['data_lectura'] = pd.to_datetime(df['data_lectura'])

In [19]:
df.sort_values(by="data_lectura", ascending=False)[:90]

,comarca,data_lectura,temp,precip,hume,temp_anterior,precip_anterior,hume_anterior
37099,Vallès Oriental,2023-07-09,25.430952,0.0,54.833333,25.474306,0.0,55.194444
26499,Maresme,2023-07-09,25.573810,0.0,62.600000,26.127778,0.0,63.458333
15899,Barcelonès,2023-07-09,26.150000,0.0,66.878378,26.226667,0.0,66.291667
31799,Vallès Occidental,2023-07-09,25.338776,0.0,63.390476,25.869048,0.0,61.208333
10599,Baix Llobregat,2023-07-09,26.210000,0.0,63.040000,26.188333,0.0,64.766667
...,...,...,...,...,...,...,...,...
21187,Garraf,2023-06-27,25.018056,0.0,77.402778,25.358333,0.0,72.000000
15887,Barcelonès,2023-06-27,25.476667,0.0,78.175000,26.617500,0.0,64.508333
5287,Alt Penedès,2023-06-27,25.192500,0.0,67.366667,26.379167,0.0,59.191667
26487,Maresme,2023-06-27,24.280556,0.0,79.013889,25.704167,0.0,64.472222
37087,Vallès Oriental,2023-06-27,23.415278,0.0,71.312500,25.342361,0.0,54.125000

In [20]:
for comarca in comarcas_df['comarca']:
    com = df[df.comarca == comarca].sort_values(by="data_lectura", ascending=False)[:270]
    json_com = com.to_json(orient='records', date_format='iso')

    file_name = f'../data_spi/{unidecode(comarca).replace(" ", "")}.json'
    with open(file_name, 'w') as file:
        file.write(json_com)

,comarca,data_lectura,temp,precip,hume,temp_anterior,precip_anterior,hume_anterior
37099,Vallès Oriental,2023-07-09,25.430952,0.0,54.833333,25.474306,0.0,55.194444
37098,Vallès Oriental,2023-07-08,25.474306,0.0,55.194444,23.202083,0.1,61.673611
37097,Vallès Oriental,2023-07-07,23.202083,0.1,61.673611,21.566667,2.3,73.333333
37096,Vallès Oriental,2023-07-06,21.566667,2.3,73.333333,20.505594,0.8,83.839161
37095,Vallès Oriental,2023-07-05,20.505594,0.8,83.839161,21.682639,0.0,75.513889
...,...,...,...,...,...,...,...,...
37014,Vallès Oriental,2023-04-15,11.426389,0.0,67.500000,11.502778,0.1,58.909722
37013,Vallès Oriental,2023-04-14,11.502778,0.1,58.909722,10.420833,0.3,55.201389
37012,Vallès Oriental,2023-04-13,10.420833,0.3,55.201389,15.054861,0.1,58.631944
37011,Vallès Oriental,2023-04-12,15.054861,0.1,58.631944,13.837500,0.0,59.486111
37010,Vallès Oriental,2023-04-11,13.837500,0.0,59.486111,13.838889,0.0,50.125000